### ISSUE TITLE
I keep getting error communicating with CoMPASS ecosystem

### ISSUE THREAD

**Issue by tommeyt** [com-pas/compas-open-scd#178]
I have installed everything using docker-compose, according to the documentation. And I keep getting error communicating with CoMPASS ecosystem.
Here is a screenshot from the deployment
![Screenshot_20](https://user-images.githubusercontent.com/111059624/184830601-cbcce25d-63e1-4648-a00e-0ad1e2f959c6.png)

**Comment by dlabordus** [comment]
Hi @tommeyt,

I need a little bit more information. 
- Did you use one of the Docker Compose files from our repository [CoMPAS Deploment](https://github.com/com-pas/compas-deployment) to start all the CoMPAS Components, including OpenSCD?
- If so, did you go to the URL `http://localhost/` using your browser and saw a login screen from KeyCloak?

If you just started CoMPAS OpenSCD from this repository some more work needs to be done, because the CoMPAS back-end services need to have a JWT Token to determine who you are and in some cases have the correct rights. And running it directly from here is more like running it in a Development mode.
For Developers there is a description in [DEVELOPMENT.md](https://github.com/com-pas/compas-open-scd/blob/main/DEVELOPMENT.md) how to run all components locally and do some kind of local integration testing.

I hope this helps a little bit to get CoMPAS working. There is a CoMPAS Community call every first Monday of the month. Next one is 5th September, see https://lists.lfenergy.org/g/CoMPAS/calendar for more info how to join.

**Comment by Sander3003** [comment]
Hi @tommeyt, Good to see you reaching out! What operating system are you using?

**Comment by tommeyt** [comment]
I am using CentOS Linux release 7.9.2009 (Core)
I used your official images
I used the following command: 
docker-compose --env-file compas/.env -f compas/docker-compose-postgresql.yml up -d --build
The .env file looks like this:
# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

COMPAS_HOSTNAME=lfenergy.dev.iskratel.mk
#COMPAS_HOSTNAME=localhost

I am not using localhost.
The problem is only when I use the import from CIM model function.

I am redirected to the correct keycloak, and I use the credentials admin / admin, which I belive are default.

**Comment by dlabordus** [comment]
> I am redirected to the correct keycloak, and I use the credentials admin / admin, which I believe are default.

Ah, I now understand what's going wrong. This user has no rights in CoMPAS. It's only the admin for KeyCloak.

You need to use one of the following 3 users:
- Username: scl-data-editor
  Password: editor
  Description: A SCL Data Editor: A user with the roles 'Create', 'Read', 'Update' and 'Delete'. This way, it has read and write access to the SCL Data Service.
- Username: scl-data-reader
  Password: reader
  Description: A SCL Data Reader: A user with the role 'Read'. This way, it only has reading access to the SCL Data Service.
- Username: scd-reader
  Password: reader
  Description: A SCD Reader: A user with the role 'Read' only on the SCD Type.

I most of the time use the first user, because it has the most rights :-)

**Comment by Sander3003** [comment]
@tommeyt let us know if the solution works!

**Comment by tommeyt** [comment]
Yes, this works, I do not get the above mentioned error message.

**Comment by Sander3003** [comment]
Let us know if you have feedback or more more questions!
