### ISSUE TITLE
Warning instead of Error in case of no NSDoc files are found; More descriptive warning message

### ISSUE THREAD

**Issue by pascalwilbrink** [com-pas/compas-open-scd#275]
When no NSDoc files are found, [a log Event and a snackbar are shown in the frontend.](https://github.com/com-pas/compas-open-scd/blob/main/packages/compas-open-scd/src/compas/CompasNsdoc.ts#L43)

The snackbar should be removed.
We should check with openscd if we want to divide logging an Error and showing the Snackbar in the bottom into 2 seperate things or that we want to add a flag to the event to skip showing the snackbar

**Comment by Sander3003** [comment]
If I open demo.compas.energy right now, this is what I see:

![image](https://github.com/com-pas/compas-open-scd/assets/7427358/ae9a542b-7c96-48dd-bc97-39caca2a826e)

The console states:
![image](https://github.com/com-pas/compas-open-scd/assets/7427358/0407c444-2311-42f0-8b7c-a33612714746)

As an CoMPAS user
I would like to see more clear warning messages
In order to judge if the tool is stable enough to build substations


Posposed solution:
Process NSD loading erros as warning
Add more detail to the waning: Cannot load file XYZ
