### ISSUE TITLE
Plugging mixin test fails sporadically

### ISSUE THREAD

**Issue by juancho0202** [com-pas/compas-open-scd#290]
**Describe the bug**
When you run your tests, sometimes you will get all tests passing successfully but sometimes you will see the following error popping out:

```terminal
❌ PluggingElement > add custom plugin dialog > adds a new editor kind plugin on add button click
      AssertionError: expected [ Array(9) ] to have a length of 10 but got 9
      + expected - actual
      
      -9
      +10
      
      at o.<anonymous> (test/unit/Plugging.test.ts:146:38)
```

**To Reproduce**
1. Run `npm test`
2. Cross fingers
3. See error

**Expected behavior**
This test should pass consistently

**Comment by Sander3003** [comment]
This might has to do with clearing the local storage.

**Comment by Stef3st** [comment]
@juancho0202 did you notice this error occuring on Open-SCD? If so, it should be moved there. If this behavior only happend in Compas-Open-SCD this ticket can be closed. 
Since we moved to a mono-repo structure the Plugging test will no longer be run in Compas, as this has already been tested within Open-SCD and will remain in that package. Only the Compas package will be tested in Compas-Open-SCD.
